variable "aws_region" {
  description = "AWS region to deploy in"
  default     = "ap-south-1"
}

variable "project_name" {
  description = "Prefix for all resources"
  default     = "mdtopdf"
}

variable "bucket_name" {
  description = "Bucket for storing the Markdown pdf generated by my Devops project"
  default = "mdtopdf-bucket-vedant-devops-2026"
}

variable "key_pair_name" {
  description = "Name of your EC2 SSH key pair (create in AWS Console)"
  default     = "mdtopdf-keypair"
}