[app_server]
13.233.65.135 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/mdtopdf-keypair.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no' ansible_python_interpreter=/usr/bin/python3
; 13.201.48.18